name: DeathWish
main: com.MoofIT.Minecraft.DeathWish.DeathWish
version: 1.0
description: A reboot of a beloved plugin on my server, HeroicDeath -- just a little more sarcastic this time. 
author: Southpaw018
website: http://www.moofit.com